import schedule from "./calendly-availability.json";

/**
 * The recurring weekly booking hours, as crawlable text.
 *
 * These are read from `calendly-availability.json`, regenerated by
 * `npm run sync:availability`. The data is deliberately durable — a weekly
 * pattern that changes only when Jesse edits his working hours — rather than
 * specific open slots, which go stale between deploys and would put a visible
 * inaccuracy on the page.
 *
 * Everything here renders as HTML on our own domain. The Calendly iframe is a
 * hole in the page as far as crawlers are concerned: nothing inside it is
 * attributed to us, so any fact worth indexing has to exist outside it too.
 */

/** Monday first, because the grouped ranges read better that way. */
const WEEK = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
] as const;

type Day = (typeof WEEK)[number];
type Interval = { from: string; to: string };

const titleCase = (day: string) => day[0].toUpperCase() + day.slice(1);

/** "09:00" -> "9am", "17:30" -> "5:30pm". */
export function clockLabel(time: string): string {
  const [hours, minutes] = time.split(":").map(Number);
  const suffix = hours < 12 ? "am" : "pm";
  const hour = hours % 12 || 12;
  return minutes ? `${hour}:${String(minutes).padStart(2, "0")}${suffix}` : `${hour}${suffix}`;
}

const intervalsFor = (day: Day): Interval[] =>
  (schedule.days as Record<string, Interval[] | undefined>)[day] ?? [];

/** Distinguishes an open day from a closed one for grouping and for copy. */
const signature = (day: Day) =>
  intervalsFor(day)
    .map(({ from, to }) => `${from}-${to}`)
    .join(",");

export type DayRange = {
  /** "Monday" or "Monday–Saturday". */
  days: string;
  /** The days in this run, for structured data. */
  dayNames: string[];
  intervals: Interval[];
  /** "9am–6pm", or "Closed" when Calendly offers nothing that day. */
  hours: string;
  closed: boolean;
};

/**
 * Collapses the week into runs of consecutive days that share the same hours,
 * so seven identical rows read as "Monday–Saturday" instead.
 */
export function weeklyHours(): DayRange[] {
  const runs: { signature: string; days: Day[] }[] = [];

  for (const day of WEEK) {
    const last = runs.at(-1);
    if (last && last.signature === signature(day)) last.days.push(day);
    else runs.push({ signature: signature(day), days: [day] });
  }

  return runs.map(({ days }) => {
    const intervals = intervalsFor(days[0]);
    const first = titleCase(days[0]);
    const last = titleCase(days[days.length - 1]);

    return {
      days: days.length === 1 ? first : `${first}–${last}`,
      dayNames: days.map(titleCase),
      intervals,
      hours:
        intervals
          .map(({ from, to }) => `${clockLabel(from)}–${clockLabel(to)}`)
          .join(", ") || "Closed",
      closed: intervals.length === 0,
    };
  });
}

/** IANA zone, for structured data and for anyone doing the maths themselves. */
export const TIMEZONE = schedule.timezone;

/**
 * Short label for prose — "ET" rather than "America/New_York".
 *
 * `shortGeneric` deliberately, not `short`: the latter resolves against a
 * specific date and would publish "EST" year-round on a winter build, which is
 * wrong for half the year. The generic form covers both halves.
 */
export const TIMEZONE_LABEL =
  new Intl.DateTimeFormat("en-US", {
    timeZone: TIMEZONE,
    timeZoneName: "shortGeneric",
  })
    .formatToParts(new Date(Date.UTC(2026, 0, 15)))
    .find((part) => part.type === "timeZoneName")?.value ?? TIMEZONE;

export const DURATION_MINUTES = schedule.durationMinutes;

/** One-line summary, used in prose and in llms.txt. */
export function hoursSentence(): string {
  const open = weeklyHours().filter((range) => !range.closed);
  if (open.length === 0) return "Booking hours are set in Calendly.";
  return `${open
    .map((range) => `${range.days} ${range.hours}`)
    .join(", and ")} ${TIMEZONE_LABEL}.`;
}
